### ISSUE TITLE
Local IP address resolution fails

### ISSUE THREAD

**Issue by wchill** [cameroncros/OctoPrint-DiscordRemote#132]
This is most likely due to my network setup (I run my home network on a 10.0.0.0/8), but it suggests that a more robust solution is needed.

```
(oprint) pi@prusa-i3:~ $ python2
Python 2.7.16 (default, Apr  6 2019, 01:42:57)
[GCC 8.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
>>> s.connect(('10.255.255.255', 1))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 13] Permission denied
```

```
(oprint) pi@prusa-i3:~ $ ip addr show dev eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether b8:27:eb:5b:be:1d brd ff:ff:ff:ff:ff:ff
    inet 10.0.130.79/8 brd 10.255.255.255 scope global dynamic noprefixroute eth0
       valid_lft 6123sec preferred_lft 5223sec
    inet6 fe80::deff:1a44:c5d8:2416/64 scope link
       valid_lft forever preferred_lft forever
```

**Comment by cameroncros** [comment]
can you try the same code but with a different address to 10.255.255.255? Maybe 192.168.1.1?
