### ISSUE TITLE
Updating to 3.11.0 causes discordremote to no longer show up as installed and unable to be configured.

### ISSUE THREAD

**Issue by bharvey88** [cameroncros/OctoPrint-DiscordRemote#233]
**Describe the bug**
Once I updated discordremote to 3.11.0 and restarted I noticed my discord bot was offline. I restarted the pi and it still wasnt back so I went into the octoprint ui and discordremote didnt show as installed. So I then reinstalled, then restarted, and still the plugin doesnt show installed. https://imgur.com/6Zs17Ug here is a picture showing octoprint shows "unknown" was installed successfully in top right.

*Logs*
Please find the logs and upload them here. It'll likely be the first thing that is asked for, so save some time and upload them. Logs can be found under Settings -> Logging -> plugin_discordremote.log

the only logs found in above location for the plugin are from before the update. possibly due to octoprint not properly seeing the plugin installed correctly.

octoprint.log shows this:

2023-01-08 08:17:27,420 - octoprint.plugin.core - ERROR - Error loading plugin discordremote
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/core.py", line 1274, in _import_plugin
    module = _load_module(module_name, spec)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/core.py", line 52, in _load_module
    return imp.load_module(name, f, filename, details)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/vendor/imp.py", line 238, in load_module
    return load_package(name, filename)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/vendor/imp.py", line 212, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_discordremote/__init__.py", line 26, in <module>
    from octoprint_discordremote.command import Command
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_discordremote/command.py", line 16, in <module>
    from discord.embeds import Embed
  File "/home/pi/oprint/lib/python3.7/site-packages/discord/__init__.py", line 25, in <module>
    from .client import Client
  File "/home/pi/oprint/lib/python3.7/site-packages/discord/client.py", line 35, in <module>
    from .user import User, Profile
  File "/home/pi/oprint/lib/python3.7/site-packages/discord/user.py", line 29, in <module>
    import discord.abc
  File "/home/pi/oprint/lib/python3.7/site-packages/discord/abc.py", line 32, in <module>
    from .iterators import HistoryIterator
  File "/home/pi/oprint/lib/python3.7/site-packages/discord/iterators.py", line 33, in <module>
    from .audit_logs import AuditLogEntry
  File "/home/pi/oprint/lib/python3.7/site-packages/discord/audit_logs.py", line 27, in <module>
    from . import utils, enums
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
ValueError: bad marshal data (invalid reference)

**To Reproduce**
1. update discord remote
2. restart octoprint
3. discord remote is now not showing up as installed and unable to be configured.

**Expected behavior**
Update succeeds and plugin still works.

**Screenshots**
https://imgur.com/6Zs17Ug here is a picture showing octoprint shows "unknown" was installed successfully in top right.

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser firefox
 - Version latest stable

**Additional context**
none needed

**Comment by bharvey88** [comment]
follow up - I spoke to jneilliii (octoprint / plugin dev) and he suggested trying this command via cli "/home/pi/oprint/bin/pip install --force-reinstall --no-cache-dir https://github.com/cameroncros/OctoPrint-DiscordRemote/archive/refs/tags/v3.11.0.zip" and after rebooting the plugin is now showing back up and working.

**Comment by bharvey88** [comment]
second follow up - succeeded upgrading second printer plugin with no issues. Possibly a corruption issue on sd card. I wont close this just in case you think it might be worth looking into, but if you agree it's most likely just a corruption issue then please feel free to close it.

**Comment by cameroncros** [comment]
Im happy to close the issue, If I cannot replicate it then I cant really debug it, and it seems like you solved it for yourself anyway.
